[favicon]
filename = "favicon.png"
license = "CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0/>"
credit = "Redpendrew <https://github.com/Redpendrew>"
sidenote = "This file is located in the root directory, 'docs'."

[color-terminal]
filename = "color-terminal.jpg"
license = "CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0/>"
credit = "Average Linux User <https://averagelinuxuser.com/linux-terminal-color/>"

[ecterm-1200]
filename = "ecterm-1200.png"
license = "CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0/>"
credit = "Redpendrew <https://github.com/Redpendrew>"

[ecterm]
filename = "ecterm.png"
license = "CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0/>"
credit = "Redpendrew <https://github.com/Redpendrew>"

[github-mark-light]
filename = "github-mark-light.png"
license = "All rights reserved <https://github.com/logos>"
credit = "GitHub <https://github.com/>"

[insert-cell]
filename = "insert-cell.png"
license = "Public Domain"
credit = "N/A"

[lightbulb-tablet]
filename = "lightbulb-tablet.jpg"
license = "Public Domain"
credit = "N/A"

[rust]
filename = "rust.png"
license = "CC BY 4.0 <https://creativecommons.org/licenses/by/4.0>"
credit = "Mozilla Foundation <https://foundation.mozilla.org/en/>"

[rustacean]
filename = "rustacean.png"
license = "Public Domain"
credit = "N/A"

[tango-terminal]
filename = "tango-terminal.png"
license = "Public Domain"
credit = "N/A"